/**
 * Precondition checks for the CTFS export endpoint.
 *
 * Implements the "Finished Census" gate from the spec (section "App-Side Export Endpoint",
 * precondition checks 1-8). Must pass before a CTFS SQL artifact is generated.
 *
 * Each check runs as a parameterized query against the app schema (schema-qualified
 * identifiers via `quoteSchema`; CensusID bound via `?` placeholder). Schema names
 * are validated against a strict regex before being backtick-quoted, preventing
 * SQL injection through schema name interpolation.
 */

import type { Connection } from 'mysql2/promise';
import { exportableMeasurementBaseWhere } from './exportable-measurement';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const MAX_DISPLAY_FAILURES = 50;

// Backtick-quoting a schema name is safe only when the name is restricted to
// letters, digits, and underscores. MySQL allows broader identifier characters,
// but the app's schema names are generated by provisioning code and always
// follow this pattern.
const SCHEMA_NAME_RE = /^[A-Za-z][A-Za-z0-9_]*$/;

// CTFS destination column widths that bound source values at export time.
const CTFS_LIMITS = {
  treeTag: 10,
  stemTag: 32,
  quadratName: 8,
  tsmCode: 10,
  dbhComments: 128,
  speciesMnemonic: 10,
  taxonomyName: 64,
  taxonomyAuthority: 128
} as const;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type PreconditionFailureKind =
  | 'not-validated'
  | 'unresolved-error'
  | 'no-stem-guid'
  | 'inactive-join'
  | 'unknown-attribute-code'
  | 'missing-taxonomy-fields'
  | 'string-too-long'
  | 'zero-exportable-rows';

export interface PreconditionFailure {
  kind: PreconditionFailureKind;
  message: string;
  /** CoreMeasurementIDs of disqualifying rows, capped at MAX_DISPLAY_FAILURES. */
  coreMeasurementIds: number[];
}

export interface PreconditionInput {
  schema: string;
  plotId: number;
  censusId: number;
}

export type PreconditionResult = { ok: true; count: number } | { ok: false; reasons: PreconditionFailure[] };

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Validate and backtick-quote a MySQL schema name for use as a SQL identifier.
 * Throws on names that contain non-identifier characters to prevent injection.
 */
function quoteSchema(schema: string): string {
  if (!SCHEMA_NAME_RE.test(schema)) {
    throw new Error(`Invalid schema name: ${schema}`);
  }
  return `\`${schema}\``;
}

/**
 * Execute a query and return the first MAX_DISPLAY_FAILURES CoreMeasurementIDs.
 * The query must SELECT CoreMeasurementID as the first column.
 */
async function gatherIds(conn: Connection, sql: string, params: unknown[]): Promise<number[]> {
  const [rows] = await conn.query<any[]>(sql, params);
  return (rows as Array<{ CoreMeasurementID: number }>).slice(0, MAX_DISPLAY_FAILURES).map(r => Number(r.CoreMeasurementID));
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Run all 8 "Finished Census" precondition checks against `(schema, censusId)`.
 *
 * Returns `{ ok: true, count }` when no disqualifying rows exist, where `count`
 * is the number of exportable measurements. Returns `{ ok: false, reasons }` with
 * one `PreconditionFailure` per triggered check.
 *
 * All queries use parameterized `?` for the censusId and backtick-quoted schema
 * names (validated by regex). No raw string concatenation of user-supplied values.
 */
export async function checkFinishedCensus(conn: Connection, input: PreconditionInput): Promise<PreconditionResult> {
  const s = quoteSchema(input.schema);
  const reasons: PreconditionFailure[] = [];
  // Fetch one extra row beyond the display cap so we can detect overflow without
  // fetching an unbounded result set.
  const fetchLimit = MAX_DISPLAY_FAILURES + 1;

  // Check 1: IsValidated IS NOT TRUE
  // Must use `IS NULL OR = FALSE` rather than `<> TRUE` — SQL three-valued logic
  // would silently pass NULL through a <> comparison.
  const notValidatedIds = await gatherIds(
    conn,
    `SELECT CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (IsValidated IS NULL OR IsValidated = FALSE)
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (notValidatedIds.length > 0) {
    reasons.push({
      kind: 'not-validated',
      message: 'Measurements not validated (IsValidated is FALSE or NULL)',
      coreMeasurementIds: notValidatedIds
    });
  }

  // Check 2: Unresolved measurement_error_log row.
  const unresolvedIds = await gatherIds(
    conn,
    `SELECT DISTINCT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.measurement_error_log mel ON mel.MeasurementID = cm.CoreMeasurementID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND COALESCE(mel.IsResolved, FALSE) = FALSE
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (unresolvedIds.length > 0) {
    reasons.push({
      kind: 'unresolved-error',
      message: 'Unresolved measurement_error_log rows exist',
      coreMeasurementIds: unresolvedIds
    });
  }

  // Check 3: StemGUID IS NULL (app-side failure marker).
  const noStemIds = await gatherIds(
    conn,
    `SELECT CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND StemGUID IS NULL
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (noStemIds.length > 0) {
    reasons.push({
      kind: 'no-stem-guid',
      message: 'Measurements lack StemGUID (app-side failure marker)',
      coreMeasurementIds: noStemIds
    });
  }

  // Check 4: Joined stems or trees is inactive or soft-deleted.
  const inactiveIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems st ON st.StemGUID = cm.StemGUID
       JOIN ${s}.trees t  ON t.TreeID    = st.TreeID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          st.IsActive = 0 OR st.DeletedAt IS NOT NULL
          OR t.IsActive = 0 OR t.DeletedAt IS NOT NULL
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (inactiveIds.length > 0) {
    reasons.push({
      kind: 'inactive-join',
      message: 'Joined stems or trees are inactive or soft-deleted',
      coreMeasurementIds: inactiveIds
    });
  }

  // Check 5: cmattributes.Code does not resolve to an active app attributes row.
  // The app has no FK from cmattributes.Code to attributes.Code (by design, to allow
  // display of invalid codes for correction), so this must be checked explicitly.
  // attributes PK is (Code, IsActive), so require IsActive = 1 on the join.
  const unknownAttrIds = await gatherIds(
    conn,
    `SELECT DISTINCT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.cmattributes cma ON cma.CoreMeasurementID = cm.CoreMeasurementID
       LEFT JOIN ${s}.attributes a ON a.Code = cma.Code AND a.IsActive = 1
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND a.Code IS NULL
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (unknownAttrIds.length > 0) {
    reasons.push({
      kind: 'unknown-attribute-code',
      message: 'cmattributes.Code does not resolve to an active app attributes row',
      coreMeasurementIds: unknownAttrIds
    });
  }

  // Check 6: Missing taxonomy fields needed for destination lookup.
  // Required: SpeciesCode, SpeciesName, genus.Genus, family.Family.
  // Subspecies rows (SubspeciesName IS NOT NULL) are allowed — they get a destination
  // SubSpecies lookup; the check does not reject them.
  const missingTaxonomyIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems   st  ON st.StemGUID  = cm.StemGUID
       JOIN ${s}.trees   t   ON t.TreeID     = st.TreeID
       JOIN ${s}.species sp  ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus   gn  ON gn.GenusID   = sp.GenusID
       JOIN ${s}.family  fam ON fam.FamilyID = gn.FamilyID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          sp.SpeciesCode IS NULL OR sp.SpeciesCode = ''
          OR sp.SpeciesName IS NULL  OR sp.SpeciesName = ''
          OR gn.Genus       IS NULL  OR gn.Genus = ''
          OR fam.Family     IS NULL  OR fam.Family = ''
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (missingTaxonomyIds.length > 0) {
    reasons.push({
      kind: 'missing-taxonomy-fields',
      message: 'Species row is missing taxonomy fields required for destination lookup (SpeciesCode, SpeciesName, Genus, Family)',
      coreMeasurementIds: missingTaxonomyIds
    });
  }

  // Check 7: Destination-bound value exceeds CTFS legacy column width.
  // Source column widths in the app schema may be larger than CTFS column widths.
  // Specific limits (from spec):
  //   Tree.Tag 10, Stem.StemTag 32, Quadrat.QuadratName 8, TSMAttributes.TSMCode 10,
  //   DBH.Comments 128, Species.Mnemonic / SubSpecies.Mnemonic 10,
  //   taxonomy names 64, taxonomy authorities 128.
  // App coremeasurements.Description maps to CTFS DBH.Comments (128 char limit).
  // App species.SpeciesCode maps to CTFS Mnemonic (10 char limit).
  const tooLongIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems   st  ON st.StemGUID  = cm.StemGUID
       JOIN ${s}.trees   t   ON t.TreeID     = st.TreeID
       JOIN ${s}.quadrats q  ON q.QuadratID  = st.QuadratID
       JOIN ${s}.species sp  ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus   gn  ON gn.GenusID   = sp.GenusID
       JOIN ${s}.family  fam ON fam.FamilyID = gn.FamilyID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          CHAR_LENGTH(t.TreeTag)                        > ${CTFS_LIMITS.treeTag}
          OR CHAR_LENGTH(st.StemTag)                    > ${CTFS_LIMITS.stemTag}
          OR CHAR_LENGTH(q.QuadratName)                 > ${CTFS_LIMITS.quadratName}
          OR CHAR_LENGTH(COALESCE(cm.Description, ''))  > ${CTFS_LIMITS.dbhComments}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesCode, ''))  > ${CTFS_LIMITS.speciesMnemonic}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesName, ''))  > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(sp.SubspeciesName, '')) > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(gn.Genus, ''))        > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(fam.Family, ''))      > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesAuthority, ''))    > ${CTFS_LIMITS.taxonomyAuthority}
          OR CHAR_LENGTH(COALESCE(sp.SubspeciesAuthority, '')) > ${CTFS_LIMITS.taxonomyAuthority}
          OR CHAR_LENGTH(COALESCE(gn.GenusAuthority, ''))      > ${CTFS_LIMITS.taxonomyAuthority}
          OR EXISTS (
            SELECT 1
              FROM ${s}.cmattributes cma
             WHERE cma.CoreMeasurementID = cm.CoreMeasurementID
               AND CHAR_LENGTH(COALESCE(cma.Code, '')) > ${CTFS_LIMITS.tsmCode}
          )
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (tooLongIds.length > 0) {
    reasons.push({
      kind: 'string-too-long',
      message: 'Destination-bound value exceeds CTFS legacy column width',
      coreMeasurementIds: tooLongIds
    });
  }

  // If any checks failed, return the accumulated failure list immediately.
  // Check 8 (zero rows) only makes sense when no other disqualifiers exist.
  if (reasons.length > 0) {
    return { ok: false, reasons };
  }

  // Check 8: Zero exportable rows remain after all filters. Uses the shared
  // "exportable measurement" base WHERE so this precondition matches the
  // filter that selectMeasurements applies — preventing drift between "I
  // would let you export this" and "here's what would actually export."
  // Aliases: cm = coremeasurements, c = census, s = stems, t = trees (matching
  // exportableMeasurementBaseWhere conventions). Bound params: [censusId, plotId].
  const [countRows] = await conn.query<any[]>(
    `SELECT COUNT(*) AS n
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems s  ON s.StemGUID = cm.StemGUID
       JOIN ${s}.trees t  ON t.TreeID   = s.TreeID
      WHERE ${exportableMeasurementBaseWhere}`,
    [input.censusId, input.plotId]
  );
  const count = Number((countRows as Array<{ n: number }>)[0].n);

  if (count === 0) {
    return {
      ok: false,
      reasons: [
        {
          kind: 'zero-exportable-rows',
          message: 'No exportable rows remain after applying all filters',
          coreMeasurementIds: []
        }
      ]
    };
  }

  return { ok: true, count };
}
