/**
 * Precondition checks for the CTFS export endpoint.
 *
 * Implements the "Finished Census" gate from the spec (section "App-Side Export Endpoint",
 * precondition checks 1-8). Must pass before a CTFS SQL artifact is generated.
 *
 * Each check runs as a parameterized query against the app schema (schema-qualified
 * identifiers via `quoteSchema`; CensusID bound via `?` placeholder). Schema names
 * are validated against a strict regex before being backtick-quoted, preventing
 * SQL injection through schema name interpolation.
 *
 * Task 10C (ratified interim 2026-07-20 — IMPLEMENTED): publish preconditions are split
 * into WARNING vs BLOCKING kinds (see WARNING_PRECONDITION_KINDS below). Data-quality
 * failures surface as warnings and the publish proceeds; destination-integrity failures
 * still 400. The classification lives in this module and the gating in the CTFS export
 * route; a dry run continues to surface everything as a preview.
 *
 * TODO (full validation-tier feature, still deferred): an authorized, AUDITED operator
 * override that can consciously publish past a destination-integrity blocker, enforced
 * server-side so stale UI cannot bypass it. Until that exists, the blocking kinds are a
 * hard stop — do NOT reclassify any of them to a warning to work around a stuck publish,
 * because a warning-only export of those kinds ships broken data to the on-prem CTFS MySQL.
 */

import type { Connection } from 'mysql2/promise';
import { exportableMeasurementBaseWhere } from './exportable-measurement';
import { TREE_TAG_MAX_WIDTH } from '../csv-to-sql-v2';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const MAX_DISPLAY_FAILURES = 50;

/**
 * Minimum fraction of a census's active measurements that must be exportable for a
 * real publish to proceed. Below this, the publish blocks with
 * `insufficient-exportable-rows` instead of silently shipping a sliver of the census
 * as an apparent success (e.g. a census that is 99.7% unvalidated would otherwise
 * publish 0.3% of its rows and report success). Quality warnings still cover smaller
 * shortfalls — this gate only catches the "most of the census is missing" case.
 */
export const MIN_EXPORTABLE_FRACTION = 0.5;

// Backtick-quoting a schema name is safe only when the name is restricted to
// letters, digits, and underscores. MySQL allows broader identifier characters,
// but the app's schema names are generated by provisioning code and always
// follow this pattern.
const SCHEMA_NAME_RE = /^[A-Za-z][A-Za-z0-9_]*$/;

// CTFS destination column widths that bound source values at export time.
// treeTag is shared with the generated procedure's Stage 0 probe and Stage 5
// length check via TREE_TAG_MAX_WIDTH so the gates can never drift.
const CTFS_LIMITS = {
  treeTag: TREE_TAG_MAX_WIDTH,
  stemTag: 32,
  quadratName: 8,
  tsmCode: 10,
  dbhComments: 128,
  speciesMnemonic: 10,
  taxonomyName: 64,
  taxonomyAuthority: 128
} as const;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type PreconditionFailureKind =
  | 'not-validated'
  | 'unresolved-error'
  | 'no-stem-guid'
  | 'inactive-join'
  | 'unknown-attribute-code'
  | 'missing-taxonomy-fields'
  | 'string-too-long'
  | 'zero-exportable-rows'
  | 'insufficient-exportable-rows';

export interface PreconditionFailure {
  kind: PreconditionFailureKind;
  message: string;
  /** CoreMeasurementIDs of disqualifying rows, capped at MAX_DISPLAY_FAILURES. */
  coreMeasurementIds: number[];
}

export interface PreconditionInput {
  schema: string;
  plotId: number;
  censusId: number;
}

/**
 * `count` is the number of exportable measurements and `totalActiveCount` the number of
 * active measurements in the census (exportable or not). Both are always present: all
 * checks run so dry-run previews and audit events report the complete failure set and
 * exact shortfall.
 */
export type PreconditionResult =
  | { ok: true; count: number; totalActiveCount: number }
  | { ok: false; reasons: PreconditionFailure[]; count: number; totalActiveCount: number };

/**
 * Publish-gate policy (Task 10C, ratified 2026-07-20: "warn on quality, keep structural
 * blocking"). Two kinds of precondition failure:
 *
 *  - WARNING kinds are data-quality notices about rows the export ALREADY excludes via
 *    exportableMeasurementBaseWhere (IsValidated=TRUE, StemGUID NOT NULL, active joins).
 *    Surfacing them and letting the publish proceed drops nothing the artifact would have
 *    carried — the operator is simply told which rows won't be exported.
 *  - BLOCKING kinds are destination-integrity constraints. An artifact that violates them
 *    fails to load into, or silently truncates data in, the on-prem CTFS MySQL:
 *      • unknown-attribute-code — the row IS exported (base WHERE does not filter on
 *        attributes) carrying a code the destination's TSMAttributes cannot resolve;
 *      • missing-taxonomy-fields — the destination species/genus/family lookup fails;
 *      • string-too-long — a value overflows a narrower CTFS column;
 *      • zero-exportable-rows — an empty/meaningless artifact;
 *      • insufficient-exportable-rows — quality exclusions leave less than
 *        MIN_EXPORTABLE_FRACTION of the census's active rows, so a "successful" publish
 *        would silently omit most of the census.
 *    These stay blocking so the "warn, don't block" relaxation can never ship broken data
 *    to CTFS.
 */
export const WARNING_PRECONDITION_KINDS: ReadonlySet<PreconditionFailureKind> = new Set<PreconditionFailureKind>([
  'not-validated',
  'unresolved-error',
  'no-stem-guid',
  'inactive-join'
]);

export function isBlockingPreconditionKind(kind: PreconditionFailureKind): boolean {
  return !WARNING_PRECONDITION_KINDS.has(kind);
}

/**
 * Split precondition failures into the ones that must block a real publish and the ones
 * that only warrant a warning. Preserves input order within each bucket.
 */
export function partitionPreconditionFailures(reasons: PreconditionFailure[]): {
  blocking: PreconditionFailure[];
  warnings: PreconditionFailure[];
} {
  const blocking: PreconditionFailure[] = [];
  const warnings: PreconditionFailure[] = [];
  for (const reason of reasons) {
    (isBlockingPreconditionKind(reason.kind) ? blocking : warnings).push(reason);
  }
  return { blocking, warnings };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Validate and backtick-quote a MySQL schema name for use as a SQL identifier.
 * Throws on names that contain non-identifier characters to prevent injection.
 */
function quoteSchema(schema: string): string {
  if (!SCHEMA_NAME_RE.test(schema)) {
    throw new Error(`Invalid schema name: ${schema}`);
  }
  return `\`${schema}\``;
}

/**
 * Execute a query and return the first MAX_DISPLAY_FAILURES CoreMeasurementIDs.
 * The query must SELECT CoreMeasurementID as the first column.
 */
async function gatherIds(conn: Connection, sql: string, params: unknown[]): Promise<number[]> {
  const [rows] = await conn.query<any[]>(sql, params);
  return (rows as Array<{ CoreMeasurementID: number }>).slice(0, MAX_DISPLAY_FAILURES).map(r => Number(r.CoreMeasurementID));
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Run all 8 "Finished Census" precondition checks against `(schema, censusId)`.
 *
 * Returns `{ ok: true, count, totalActiveCount }` when no disqualifying rows exist,
 * where `count` is the number of exportable measurements and `totalActiveCount` the
 * number of active measurements in the census. Returns `{ ok: false, reasons }` with
 * one `PreconditionFailure` per triggered check (plus both counts when check 8 ran).
 *
 * All queries use parameterized `?` for the censusId and backtick-quoted schema
 * names (validated by regex). No raw string concatenation of user-supplied values.
 */
export async function checkFinishedCensus(conn: Connection, input: PreconditionInput): Promise<PreconditionResult> {
  const s = quoteSchema(input.schema);
  const reasons: PreconditionFailure[] = [];
  // Fetch one extra row beyond the display cap so we can detect overflow without
  // fetching an unbounded result set.
  const fetchLimit = MAX_DISPLAY_FAILURES + 1;

  // Check 1: IsValidated IS NOT TRUE
  // Must use `IS NULL OR = FALSE` rather than `<> TRUE` — SQL three-valued logic
  // would silently pass NULL through a <> comparison.
  const notValidatedIds = await gatherIds(
    conn,
    `SELECT CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (IsValidated IS NULL OR IsValidated = FALSE)
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (notValidatedIds.length > 0) {
    reasons.push({
      kind: 'not-validated',
      message: 'Measurements not validated (IsValidated is FALSE or NULL)',
      coreMeasurementIds: notValidatedIds
    });
  }

  // Check 2: Unresolved measurement_error_log row.
  const unresolvedIds = await gatherIds(
    conn,
    `SELECT DISTINCT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.measurement_error_log mel ON mel.MeasurementID = cm.CoreMeasurementID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND COALESCE(mel.IsResolved, FALSE) = FALSE
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (unresolvedIds.length > 0) {
    reasons.push({
      kind: 'unresolved-error',
      message: 'Unresolved measurement_error_log rows exist',
      coreMeasurementIds: unresolvedIds
    });
  }

  // Check 3: StemGUID IS NULL (app-side failure marker).
  const noStemIds = await gatherIds(
    conn,
    `SELECT CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND StemGUID IS NULL
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (noStemIds.length > 0) {
    reasons.push({
      kind: 'no-stem-guid',
      message: 'Measurements lack StemGUID (app-side failure marker)',
      coreMeasurementIds: noStemIds
    });
  }

  // Check 4: Joined stems or trees is inactive or soft-deleted.
  const inactiveIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems st ON st.StemGUID = cm.StemGUID
       JOIN ${s}.trees t  ON t.TreeID    = st.TreeID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          st.IsActive = 0 OR st.DeletedAt IS NOT NULL
          OR t.IsActive = 0 OR t.DeletedAt IS NOT NULL
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (inactiveIds.length > 0) {
    reasons.push({
      kind: 'inactive-join',
      message: 'Joined stems or trees are inactive or soft-deleted',
      coreMeasurementIds: inactiveIds
    });
  }

  // Check 5: cmattributes.Code does not resolve to an active app attributes row.
  // The app has no FK from cmattributes.Code to attributes.Code (by design, to allow
  // display of invalid codes for correction), so this must be checked explicitly.
  // attributes PK is (Code, IsActive), so require IsActive = 1 on the join.
  const unknownAttrIds = await gatherIds(
    conn,
    `SELECT DISTINCT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.cmattributes cma ON cma.CoreMeasurementID = cm.CoreMeasurementID
       LEFT JOIN ${s}.attributes a ON a.Code = cma.Code AND a.IsActive = 1
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND a.Code IS NULL
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (unknownAttrIds.length > 0) {
    reasons.push({
      kind: 'unknown-attribute-code',
      message: 'cmattributes.Code does not resolve to an active app attributes row',
      coreMeasurementIds: unknownAttrIds
    });
  }

  // Check 6: Missing taxonomy fields needed for destination lookup.
  // Required: SpeciesCode, SpeciesName, genus.Genus, family.Family.
  // Subspecies rows (SubspeciesName IS NOT NULL) are allowed — they get a destination
  // SubSpecies lookup; the check does not reject them.
  const missingTaxonomyIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems   st  ON st.StemGUID  = cm.StemGUID
       JOIN ${s}.trees   t   ON t.TreeID     = st.TreeID
       JOIN ${s}.species sp  ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus   gn  ON gn.GenusID   = sp.GenusID
       JOIN ${s}.family  fam ON fam.FamilyID = gn.FamilyID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          sp.SpeciesCode IS NULL OR sp.SpeciesCode = ''
          OR sp.SpeciesName IS NULL  OR sp.SpeciesName = ''
          OR gn.Genus       IS NULL  OR gn.Genus = ''
          OR fam.Family     IS NULL  OR fam.Family = ''
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (missingTaxonomyIds.length > 0) {
    reasons.push({
      kind: 'missing-taxonomy-fields',
      message: 'Species row is missing taxonomy fields required for destination lookup (SpeciesCode, SpeciesName, Genus, Family)',
      coreMeasurementIds: missingTaxonomyIds
    });
  }

  // Check 7: Destination-bound value exceeds CTFS legacy column width.
  // Source column widths in the app schema may be larger than CTFS column widths.
  // Specific limits (from spec):
  //   Tree.Tag 20, Stem.StemTag 32, Quadrat.QuadratName 8, TSMAttributes.TSMCode 10,
  //   DBH.Comments 128, Species.Mnemonic / SubSpecies.Mnemonic 10,
  //   taxonomy names 64, taxonomy authorities 128.
  // App coremeasurements.Description maps to CTFS DBH.Comments (128 char limit).
  // App species.SpeciesCode maps to CTFS Mnemonic (10 char limit).
  const tooLongIds = await gatherIds(
    conn,
    `SELECT cm.CoreMeasurementID
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems   st  ON st.StemGUID  = cm.StemGUID
       JOIN ${s}.trees   t   ON t.TreeID     = st.TreeID
       JOIN ${s}.quadrats q  ON q.QuadratID  = st.QuadratID
       JOIN ${s}.species sp  ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus   gn  ON gn.GenusID   = sp.GenusID
       JOIN ${s}.family  fam ON fam.FamilyID = gn.FamilyID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1
        AND (
          CHAR_LENGTH(t.TreeTag)                        > ${CTFS_LIMITS.treeTag}
          OR CHAR_LENGTH(st.StemTag)                    > ${CTFS_LIMITS.stemTag}
          OR CHAR_LENGTH(q.QuadratName)                 > ${CTFS_LIMITS.quadratName}
          OR CHAR_LENGTH(COALESCE(cm.Description, ''))  > ${CTFS_LIMITS.dbhComments}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesCode, ''))  > ${CTFS_LIMITS.speciesMnemonic}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesName, ''))  > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(sp.SubspeciesName, '')) > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(gn.Genus, ''))        > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(fam.Family, ''))      > ${CTFS_LIMITS.taxonomyName}
          OR CHAR_LENGTH(COALESCE(sp.SpeciesAuthority, ''))    > ${CTFS_LIMITS.taxonomyAuthority}
          OR CHAR_LENGTH(COALESCE(sp.SubspeciesAuthority, '')) > ${CTFS_LIMITS.taxonomyAuthority}
          OR CHAR_LENGTH(COALESCE(gn.GenusAuthority, ''))      > ${CTFS_LIMITS.taxonomyAuthority}
          OR EXISTS (
            SELECT 1
              FROM ${s}.cmattributes cma
             WHERE cma.CoreMeasurementID = cm.CoreMeasurementID
               AND CHAR_LENGTH(COALESCE(cma.Code, '')) > ${CTFS_LIMITS.tsmCode}
          )
        )
      LIMIT ?`,
    [input.plotId, input.censusId, fetchLimit]
  );
  if (tooLongIds.length > 0) {
    reasons.push({
      kind: 'string-too-long',
      message: 'Destination-bound value exceeds CTFS legacy column width',
      coreMeasurementIds: tooLongIds
    });
  }

  // Check 8: Zero (or too few) exportable rows remain after all filters. Uses the
  // same full join graph and shared WHERE clause as selectMeasurements. The joins
  // beyond stems/trees matter because their foreign keys are nullable: counting a
  // validated row with no quadrat/species/taxonomy join would otherwise let the gate
  // pass even though the actual export silently drops that row.
  // Bound params: [censusId, plotId].
  const [countRows] = await conn.query<any[]>(
    `SELECT COUNT(*) AS n
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
       JOIN ${s}.stems s  ON s.StemGUID = cm.StemGUID
       JOIN ${s}.trees t  ON t.TreeID   = s.TreeID
       JOIN ${s}.quadrats q  ON q.QuadratID = s.QuadratID
       JOIN ${s}.species sp  ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus gn    ON gn.GenusID = sp.GenusID
       JOIN ${s}.family fam  ON fam.FamilyID = gn.FamilyID
      WHERE ${exportableMeasurementBaseWhere}`,
    [input.censusId, input.plotId]
  );
  const count = Number((countRows as Array<{ n: number }>)[0].n);

  const [totalRows] = await conn.query<any[]>(
    `SELECT COUNT(*) AS n
       FROM ${s}.coremeasurements cm
       JOIN ${s}.census c ON c.CensusID = cm.CensusID
      WHERE c.PlotID = ? AND cm.CensusID = ? AND cm.IsActive = 1`,
    [input.plotId, input.censusId]
  );
  const totalActiveCount = Number((totalRows as Array<{ n: number }>)[0].n);

  if (count === 0) {
    // Preserve any accumulated WARNING reasons alongside the blocking zero-rows
    // failure so the operator sees the full picture (what's wrong AND that nothing
    // is left to export).
    reasons.push({
      kind: 'zero-exportable-rows',
      message: 'No exportable rows remain after applying all filters',
      coreMeasurementIds: []
    });
    return { ok: false, reasons, count, totalActiveCount };
  }

  // A census where quality exclusions eat the majority of the rows must not publish
  // as an apparent success — the WARNING kinds above only describe what the export
  // excludes, and on a real publish they surface in a dismissible header. Blocking
  // here forces the operator to resolve the exclusions (or consciously dry-run)
  // instead of shipping a fraction of the census.
  if (count < totalActiveCount * MIN_EXPORTABLE_FRACTION) {
    const excluded = totalActiveCount - count;
    const percent = ((count / totalActiveCount) * 100).toFixed(1);
    reasons.push({
      kind: 'insufficient-exportable-rows',
      message:
        `Only ${count} of ${totalActiveCount} active measurements are exportable (${percent}%); ` +
        `publishing would silently omit ${excluded} rows. A real publish requires at least ` +
        `${MIN_EXPORTABLE_FRACTION * 100}% of the census to be exportable.`,
      coreMeasurementIds: []
    });
    return { ok: false, reasons, count, totalActiveCount };
  }

  // Rows exist. If only WARNING reasons accumulated, the census is not perfectly
  // clean (ok=false) but nothing here is blocking — the route surfaces these as
  // warnings and proceeds. ok=true is reserved for a fully clean census.
  if (reasons.length > 0) {
    return { ok: false, reasons, count, totalActiveCount };
  }

  return { ok: true, count, totalActiveCount };
}
