/**
 * Query the app DB and return measurement and attribute rows in the shape
 * required by `renderStage1` (staging_measurements + staging_attributes INSERT values).
 *
 * All taxonomy fields come from the `species` table directly — the app stores
 * SubspeciesName, SubspeciesAuthority, IDLevel, and SpeciesAuthority on the
 * species row itself rather than in a separate subspecies table.
 *
 * `PrimaryStem` is hardcoded to `null` in this MVP; marker-code splitting is
 * deferred per the spec.
 *
 * Schema names are validated against a strict regex and backtick-quoted before
 * interpolation. CensusID is bound via `?` placeholder. No raw user-supplied
 * values are concatenated into SQL text.
 */

import type { Connection } from 'mysql2/promise';
import type { MeasurementStagingRow, AttributeStagingRow } from '../csv-to-sql-shared';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// Mirrors the regex in precondition.ts — only identifiers generated by the
// app's provisioning code (letters, digits, underscores, letter-first) are safe
// to backtick-quote for schema interpolation.
const SCHEMA_NAME_RE = /^[A-Za-z][A-Za-z0-9_]*$/;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface SelectInput {
  schema: string;
  plotId: number;
  censusId: number;
}

export interface SelectResult {
  measurementRows: MeasurementStagingRow[];
  attributeRows: AttributeStagingRow[];
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function quoteSchema(schema: string): string {
  if (!SCHEMA_NAME_RE.test(schema)) {
    throw new Error(`Invalid schema name: ${schema}`);
  }
  return `\`${schema}\``;
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Query the app DB for a census's exportable measurements and their attribute
 * codes, returning rows shaped for `renderStage1` INSERT rendering.
 *
 * Exportable measurements satisfy:
 *   - `coremeasurements.CensusID = censusId`
 *   - `coremeasurements.IsActive = 1`
 *   - `coremeasurements.IsValidated = TRUE`
 *   - `coremeasurements.StemGUID IS NOT NULL`
 *   - Joined stem and tree are both active (`IsActive = 1`)
 *
 * Attribute rows are limited to codes that resolve to an active `attributes`
 * row (`IsActive = 1`). This mirrors precondition check 5's requirement that
 * all codes be resolvable before export is allowed.
 *
 * `TempMeasurementID` on each attribute row is the 1-based position of the
 * corresponding measurement in the returned `measurementRows` array, which
 * matches the `AUTO_INCREMENT TempID` value that MySQL will assign after
 * Stage 1 INSERT (measurements are inserted in `CoreMeasurementID ASC` order).
 */
export async function selectMeasurements(conn: Connection, input: SelectInput): Promise<SelectResult> {
  const s = quoteSchema(input.schema);

  // Query 1 — measurements with full taxonomy context.
  //
  // All subspecies fields (SubspeciesName, SubspeciesAuthority, IDLevel,
  // SpeciesAuthority) live on the species row in this app schema; there is no
  // separate subspecies table.
  //
  // stem.IsActive = 1 and tree.IsActive = 1 filters replicate the "active join"
  // gate from precondition check 4.
  const [measurementsRaw] = await conn.query<any[]>(
    `SELECT cm.CoreMeasurementID,
            cm.SourceRowIndex,
            t.TreeTag              AS Tag,
            s.StemTag,
            sp.SpeciesCode         AS Mnemonic,
            q.QuadratName,
            c.PlotCensusNumber,
            fam.Family,
            gn.Genus,
            sp.SpeciesName,
            sp.SpeciesAuthority,
            sp.SubspeciesName,
            sp.SubspeciesAuthority,
            sp.IDLevel,
            cm.MeasuredDBH         AS DBH,
            cm.MeasuredHOM         AS HOM,
            cm.MeasurementDate     AS ExactDate,
            cm.Description         AS Comments,
            s.LocalX               AS LX,
            s.LocalY               AS LY
       FROM ${s}.coremeasurements cm
       JOIN ${s}.stems   s   ON s.StemGUID  = cm.StemGUID
       JOIN ${s}.trees   t   ON t.TreeID    = s.TreeID
       JOIN ${s}.quadrats q  ON q.QuadratID = s.QuadratID
       JOIN ${s}.species  sp ON sp.SpeciesID = t.SpeciesID
       JOIN ${s}.genus    gn ON gn.GenusID  = sp.GenusID
       JOIN ${s}.family   fam ON fam.FamilyID = gn.FamilyID
       JOIN ${s}.census   c  ON c.CensusID  = cm.CensusID
      WHERE cm.CensusID  = ?
        AND cm.IsActive  = 1
        AND cm.IsValidated = TRUE
        AND cm.StemGUID IS NOT NULL
        AND s.IsActive   = 1
        AND t.IsActive   = 1
      ORDER BY cm.CoreMeasurementID`,
    [input.censusId]
  );

  const measurementRows: MeasurementStagingRow[] = measurementsRaw.map(r => ({
    CoreMeasurementID: Number(r.CoreMeasurementID),
    SourceRowIndex: r.SourceRowIndex == null ? null : Number(r.SourceRowIndex),
    Tag: String(r.Tag),
    StemTag: String(r.StemTag),
    Mnemonic: String(r.Mnemonic),
    QuadratName: String(r.QuadratName),
    PlotCensusNumber: String(r.PlotCensusNumber),
    Family: String(r.Family),
    Genus: String(r.Genus),
    SpeciesName: String(r.SpeciesName),
    SpeciesAuthority: r.SpeciesAuthority == null ? null : String(r.SpeciesAuthority),
    SubspeciesName: r.SubspeciesName == null ? null : String(r.SubspeciesName),
    SubspeciesAuthority: r.SubspeciesAuthority == null ? null : String(r.SubspeciesAuthority),
    IDLevel: r.IDLevel == null ? null : String(r.IDLevel),
    DBH: r.DBH == null ? null : Number(r.DBH),
    HOM: r.HOM == null ? null : String(r.HOM),
    ExactDate: r.ExactDate instanceof Date ? r.ExactDate.toISOString().slice(0, 10) : String(r.ExactDate),
    Comments: r.Comments == null ? null : String(r.Comments),
    LX: r.LX == null ? null : Number(r.LX),
    LY: r.LY == null ? null : Number(r.LY),
    PrimaryStem: null
  }));

  // Build CoreMeasurementID → 1-based position index for TempMeasurementID.
  // measurementRows is already sorted by CoreMeasurementID ASC (matching the
  // ORDER BY above), so idx+1 equals the AUTO_INCREMENT TempID MySQL will assign.
  const positionByCmid = new Map<number, number>();
  measurementRows.forEach((m, idx) => positionByCmid.set(m.CoreMeasurementID, idx + 1));

  // Query 2 — active attribute codes for the same exportable measurement set.
  //
  // The JOIN to `attributes a ON a.Code = cma.Code AND a.IsActive = 1` mirrors
  // precondition check 5: only codes with a live attributes row pass through.
  // The repeated WHERE filter (CensusID, IsActive, IsValidated, StemGUID, stem/tree
  // IsActive) ensures attributes are only fetched for rows that also appear in
  // measurementRows, keeping the two result sets consistent.
  const [attrsRaw] = await conn.query<any[]>(
    `SELECT cma.CoreMeasurementID,
            cma.Code AS TSMCode,
            cma.CMAID
       FROM ${s}.cmattributes cma
       JOIN ${s}.coremeasurements cm ON cm.CoreMeasurementID = cma.CoreMeasurementID
       JOIN ${s}.stems            s  ON s.StemGUID            = cm.StemGUID
       JOIN ${s}.trees            t  ON t.TreeID              = s.TreeID
       JOIN ${s}.attributes       a  ON a.Code = cma.Code AND a.IsActive = 1
      WHERE cm.CensusID    = ?
        AND cm.IsActive    = 1
        AND cm.IsValidated = TRUE
        AND cm.StemGUID   IS NOT NULL
        AND s.IsActive     = 1
        AND t.IsActive     = 1
      ORDER BY cma.CoreMeasurementID, cma.CMAID`,
    [input.censusId]
  );

  // Filter attributes to only those whose parent measurement is in the result
  // set (guards against any edge-case where the two queries diverge) and
  // resolve TempMeasurementID from the position map.
  const attributeRows: AttributeStagingRow[] = attrsRaw
    .filter(a => positionByCmid.has(Number(a.CoreMeasurementID)))
    .map(a => ({
      CoreMeasurementID: Number(a.CoreMeasurementID),
      TempMeasurementID: positionByCmid.get(Number(a.CoreMeasurementID))!,
      TSMCode: String(a.TSMCode)
    }));

  return { measurementRows, attributeRows };
}
