create
definer = azureroot@`%` procedure RefreshViewFullTable()
BEGIN
    -- Truncate the materialized table
TRUNCATE TABLE viewfulltable;

-- Insert data from the view into the materialized table
INSERT INTO viewfulltable (CoreMeasurementID,
                           MeasurementDate,
                           MeasuredDBH,
                           DBHUnits,
                           MeasuredHOM,
                           HOMUnits,
                           Description,
                           IsValidated,
                           PlotID,
                           PlotName,
                           LocationName,
                           CountryName,
                           DimensionX,
                           DimensionY,
                           PlotDimensionUnits,
                           PlotArea,
                           PlotAreaUnits,
                           PlotGlobalX,
                           PlotGlobalY,
                           PlotGlobalZ,
                           PlotCoordinateUnits,
                           PlotShape,
                           PlotDescription,
                           CensusID,
                           CensusStartDate,
                           CensusEndDate,
                           CensusDescription,
                           PlotCensusNumber,
                           QuadratID,
                           QuadratName,
                           QuadratDimensionX,
                           QuadratDimensionY,
                           QuadratDimensionUnits,
                           QuadratArea,
                           QuadratAreaUnits,
                           QuadratStartX,
                           QuadratStartY,
                           QuadratCoordinateUnits,
                           QuadratShape,
                           SubquadratID,
                           SubquadratName,
                           SubquadratDimensionX,
                           SubquadratDimensionY,
                           SubquadratDimensionUnits,
                           SubquadratX,
                           SubquadratY,
                           SubquadratCoordinateUnits,
                           TreeID,
                           TreeTag,
                           StemID,
                           StemTag,
                           StemLocalX,
                           StemLocalY,
                           StemCoordinateUnits,
                           PersonnelID,
                           FirstName,
                           LastName,
                           PersonnelRoles,
                           SpeciesID,
                           SpeciesCode,
                           SpeciesName,
                           SubspeciesName,
                           SubspeciesAuthority,
                           SpeciesIDLevel,
                           GenusID,
                           Genus,
                           GenusAuthority,
                           FamilyID,
                           Family,
                           AttributeCode,
                           AttributeDescription,
                           AttributeStatus)
SELECT cm.CoreMeasurementID,
       cm.MeasurementDate,
       cm.MeasuredDBH,
       cm.DBHUnit,
       cm.MeasuredHOM,
       cm.HOMUnit,
       cm.Description,
       cm.IsValidated,
       p.PlotID,
       p.PlotName,
       p.LocationName,
       p.CountryName,
       p.DimensionX,
       p.DimensionY,
       p.DimensionUnits,
       p.Area,
       p.AreaUnits,
       p.GlobalX,
       p.GlobalY,
       p.GlobalZ,
       p.CoordinateUnits,
       p.PlotShape,
       p.PlotDescription,
       c.CensusID,
       c.StartDate,
       c.EndDate,
       c.Description,
       c.PlotCensusNumber,
       q.QuadratID,
       q.QuadratName,
       q.DimensionX,
       q.DimensionY,
       q.DimensionUnits,
       q.Area,
       q.AreaUnits,
       q.StartX,
       q.StartY,
       q.CoordinateUnits,
       q.QuadratShape,
       sq.SubquadratID,
       sq.SubquadratName,
       sq.DimensionX,
       sq.DimensionY,
       sq.DimensionUnits,
       sq.QX,
       sq.QY,
       sq.CoordinateUnits,
       t.TreeID,
       t.TreeTag,
       s.StemID,
       s.StemTag,
       s.LocalX,
       s.LocalY,
       s.CoordinateUnits,
       per.PersonnelID,
       per.FirstName,
       per.LastName,
       r.RoleName,
       sp.SpeciesID,
       sp.SpeciesCode,
       sp.SpeciesName,
       sp.SubspeciesName,
       sp.SubspeciesAuthority,
       sp.IDLevel,
       g.GenusID,
       g.Genus,
       g.GenusAuthority,
       fam.FamilyID,
       fam.Family,
       attr.Code,
       attr.Description,
       attr.Status
FROM coremeasurements cm
         LEFT JOIN stems s ON cm.StemID = s.StemID
         LEFT JOIN trees t ON s.TreeID = t.TreeID
         LEFT JOIN species sp ON t.SpeciesID = sp.SpeciesID
         LEFT JOIN genus g ON sp.GenusID = g.GenusID
         LEFT JOIN family fam ON g.FamilyID = fam.FamilyID
         LEFT JOIN specieslimits sl ON sp.SpeciesCode = sl.SpeciesCode
         LEFT JOIN quadrats q ON s.QuadratID = q.QuadratID
         LEFT JOIN quadratpersonnel qp ON q.QuadratID = qp.QuadratID
         LEFT JOIN personnel per ON qp.PersonnelID = per.PersonnelID
         LEFT JOIN plots p ON q.PlotID = p.PlotID
         LEFT JOIN subquadrats sq ON q.QuadratID = sq.QuadratID
         LEFT JOIN census c ON cm.CensusID = c.CensusID
         LEFT JOIN roles r ON per.RoleID = r.RoleID
         LEFT JOIN cmattributes cma ON cm.CoreMeasurementID = cma.CoreMeasurementID
         LEFT JOIN attributes attr ON cma.Code = attr.Code;
END;

