set foreign_key_checks = 0;
truncate attributes;
truncate census;
truncate censusactivepersonnel;
truncate cmattributes;
truncate measurement_error_log;
-- NOTE: measurement_errors is a seed/config table — do NOT truncate it.
-- Truncating it breaks FK constraints in measurement_error_log on next insert.
truncate coremeasurements;
truncate family;
truncate genus;
truncate measurementssummary;
truncate personnel;
truncate plots;
truncate postvalidationqueries;
truncate quadrats;
truncate reference;
truncate roles;
truncate sitespecificvalidations;
truncate species;
truncate specieslimits;
truncate specimens;
truncate stems;
truncate trees;
truncate temporarymeasurements;
truncate upload_errors;
truncate unifiedchangelog;
truncate uploadintegrityalerts;
truncate uploadmetrics;
truncate validationchangelog;
truncate viewfulltable;
set foreign_key_checks = 1;
