set foreign_key_checks = 0;
truncate attributes;
truncate census;
truncate censusactivepersonnel;
truncate cmattributes;
truncate cmverrors;
truncate coremeasurements;
truncate family;
truncate genus;
truncate measurementssummary;
truncate personnel;
truncate plots;
truncate postvalidationqueries;
truncate quadrats;
truncate reference;
truncate roles;
truncate sitespecificvalidations;
truncate species;
truncate specieslimits;
truncate specimens;
truncate stems;
truncate trees;
truncate temporarymeasurements;
truncate failedmeasurements;
truncate unifiedchangelog;
truncate validationchangelog;
truncate viewfulltable;
set foreign_key_checks = 1;