export const siteConfig = {
	name: "ForestGEO",
	description: "Census data entry and validation",
	navItems: [
		{
			label: "Home",
			href: "/",
		},
    {
      label: "Browse",
      href: "/browse",
    },
    {
      label: "Reporting",
      href: "/reporting",
    },
    {
      label: "Validation",
      href: "/validation",
    }
	],
  plotItems: [
    { key: "Amacayacu", count: 16 },
    { key: "BCI", count: 40 },
    { key: "bukittimah", count: 22 },
    { key: "Cocoli", count: 39 },
    { key: "CRC", count: 1 },
    { key: "CTFS-Panama", count: 11 },
    { key: "Danum", count: 36 },
    { key: "Harvard Forest", count: 9 },
    { key: "Heishiding", count: 4 },
    { key: "HKK", count: 19 },
    { key: "ituri_all", count: 24 },
    { key: "khaochong", count: 38 },
    { key: "Korup", count: 10 },
    { key: "korup3census", count: 32 },
    { key: "Lambir", count: 35 },
    { key: "Lilly_Dickey", count: 41 },
    { key: "Luquillo", count: 25 },
    { key: "Mpala", count: 3 },
    { key: "osfdp", count: 37 },
    { key: "pasoh", count: 15 },
    { key: "Rabi", count: 17 },
    { key: "Scotty Creek", count: 8 },
    { key: "SERC", count: 7 },
    { key: "Sinharaja", count: 26 },
    { key: "Speulderbos", count: 29 },
    { key: "Stable_bukittimah", count: 27 },
    { key: "stable_pasoh", count: 28 },
    { key: "Traunstein", count: 34 },
    { key: "Tyson", count: 23 },
    { key: "UMBC", count: 18 },
    { key: "Utah", count: 30 },
    { key: "Vandermeer", count: 14 },
    { key: "wanang", count: 21 },
    { key: "Yosemite", count: 33 },
  ]
};
